# This is a basic workflow to help you get started with Actions

name: BuildReleaseOnly

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
    #- uses: warrenbuckley/Setup-MSBuild@v1
    #- uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Nugetrestore
      run: nuget restore WebApplication1.sln
      
    - name: Setup Dotnet 
      uses: actions/setup-dotnet@v1
      #with:
       # dotnet-version: '2.2.300'
      
    - name: 'Run dotnet build'
      shell: bash
      run: |
        # If your web app project is not located in your repository's root
        # Please consider using pushd to change your path
        pushd .
        dotnet build --configuration Release --output ./output
        popd
         

    # Runs a single command using the runners shell
    - name: Checkoutstep
      run: echo Checkoutstep!
  

